🌱 Add policy fuzzer
ossf/scorecard pull request #1631
Opened 2022-02-12 18:23 UTC by AdamKorcz

Adds a fuzzer for `ParseFromYAML` as discussed in https://github.com/google/oss-fuzz/pull/7269

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds a fuzz test.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

* **Other information**:

2022-02-12 19:53 UTC, evverx commented
I think it would be great to turn on CIFuzz/CFLite as well. Hopefully scorecard complaining about unpinned dependencies in scorecard :-) could help to fix issues like https://github.com/google/oss-fuzz/issues/7206 and https://github.com/google/oss-fuzz/issues/6836 a bit faster.

2022-02-12 22:13 UTC, justaugustus approved these changes
Thanks @AdamKorcz!

2022-02-12 22:29 UTC, naveensrinivasan reviewed
Thanks, we also need to update the build scripts to validate. 

If not when the API changes it isn't going to fail.

2022-02-12 22:30 UTC, naveensrinivasan commented
Please don't merge this till we have build integrated to validate the fuzz code.

2022-02-12 22:32 UTC, evverx commented
> Please don't merge this till we have build integrated to validate the fuzz code.

@naveensrinivasan https://google.github.io/oss-fuzz/getting-started/continuous-integration/ is supposed to do exactly that. I should have posted that link probably. Sorry!

2022-02-12 22:46 UTC, naveensrinivasan commented
The scorecard has to compile anytime the code changes locally to avoid breaking this. 


Here is an example of fuzzing compile target 
https://github.com/sigstore/sigstore/blob/main/Makefile

2022-02-12 22:52 UTC, evverx commented
> The scorecard has to compile anytime the code changes locally to avoid breaking this.

I agree. Ideally it should be integrated into the build process but in general I wouldn't expect extIernal contributors to always build and run all the tests/fuzzers before PRs are submitted so CIFuzz is supposed to help there.

2022-02-12 23:05 UTC, naveensrinivasan commented
The external contributors need not but the CI on GitHub should validate this.

2022-02-12 23:16 UTC, evverx commented
> The external contributors need not but the CI on GitHub should validate this.

@naveensrinivasan I completely agree with you. What I was trying to say is that in addition to that it usually makes sense to turn on CIFuzz because the build and runtime environments provided by OSS-Fuzz are different from what fuzz target normally face locally or on GitHub. For example, CIFuzz caught https://github.com/systemd/systemd/actions/runs/1833518567 today even though the fuzz targets were built and run locally and on GitHub Actions.

2022-02-12 23:20 UTC, naveensrinivasan commented
Also we need documentation as to how build this and test it. 

Does it need go-tip, Go-fuzz?

We need to refer to Go-Fuzz in the go.mod. This makes adding additional dependency. 

Probably the fuzz should be a separate module to avoid these additional dependencies. 

So my recommendation would be we discuss these options and then merge this in. 

The fuzz need not be for just a func. The goal would be to add to many targets.

2022-02-13 01:00 UTC, naveensrinivasan commented
> > The external contributors need not but the CI on GitHub should validate this.
> 
> 
> 
> @naveensrinivasan I completely agree with you. What I was trying to say is that in addition to that it usually makes sense to turn on CIFuzz because the build and runtime environments provided by OSS-Fuzz are different from what fuzz targets normally face locally or on GitHub. For example, CIFuzz caught https://github.com/systemd/systemd/actions/runs/1833518567 today even though the fuzz targets were built and run locally and on GitHub Actions.

@evverx Agreed! Thank you for the great insights 👍.

2022-02-14 02:09 UTC, naveensrinivasan requested changes
I am blocking this PR , till we have consensus. I agree with the code and it is just that we don't have the other infrastructure things to make this work , which I have discussed in detail https://github.com/ossf/scorecard/issues/1389#issuecomment-1038522409

Thank you! for the contribution

2022-02-14 15:29 UTC, azeemshaikh38 approved these changes
Thanks!

2022-03-25 02:33 UTC, closed without merging