:sparkles: Changed jsonScorecardResultV2 type Public
ossf/scorecard pull request #1682
Opened 2022-02-26 20:56 UTC by naveensrinivasan

#### What kind of change does this PR introduce?

Bug fix

- [ ] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

#### What is the new behavior (if this is a feature change)?**

- [ ] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
- Fixes https://github.com/ossf/scorecard/issues/1673

#### Special notes for your reviewer

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
Made the jsonScorecardResultV2 to public to make it easier for the consumers of Scorecard.
```

2022-02-27 15:33 UTC, justaugustus requested changes
@naveensrinivasan -- One nit about the `nolint`!

2022-02-27 15:33 UTC, justaugustus commented on pkg/json.go
>  //nolint:govet
```suggestion
```

the `nolint` is probably no longer required

2022-02-27 16:12 UTC, azeemshaikh38 approved these changes

2022-02-28 17:29 UTC, laurentsimon approved these changes
Thanks!

2022-02-28 20:05 UTC, naveensrinivasan commented
> @naveensrinivasan -- One nit about the `nolint`!

@justaugustus  Looks like that is required for fieldalingment. Can you please 👀 ?

2022-02-28 20:20 UTC, justaugustus approved these changes
> @justaugustus Looks like that is required for fieldalingment. Can you please 👀 ?

@naveensrinivasan -- Yep, I think moving the `date` field(str) to the bottom would fix it, but that's non-blocking!

2022-02-28 20:20 UTC, merged

2022-02-28 21:26 UTC, naveensrinivasan commented
> > @justaugustus Looks like that is required for fieldalingment. Can you please 👀 ?
> 
> @naveensrinivasan -- Yep, I think moving the `date` field(str) to the bottom would fix it, but that's non-blocking!

👍