Remove erroneous ref to CSV output
ossf/scorecard pull request #1813
Opened 2022-04-04 12:58 UTC by lehors

Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>

#### What kind of change does this PR introduce?

docs update

- [ x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

README claims that CSV output format is supported.

#### What is the new behavior (if this is a feature change)?**

README only lists default and json as output formats.

- [ ] Tests for the changes have been added (for bug fixes/features)

NA.

#### Which issue(s) this PR fixes

NONE

#### Special notes for your reviewer

I actually happen to regret the drop of CSV output support but at least the documentation should be consistent with the code.

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

Yes, the README no longer misleads the user.

```release-note
Update README to reflect actual list of supported output formats.
```

2022-04-04 13:00 UTC, naveensrinivasan approved these changes
Thanks

2022-04-04 14:20 UTC, justaugustus requested changes
Tiny nits on the language.
In addition to mentioning the format options, we should specify what `default` actually means (outputting as a table).

Could you mention this in the flags as well?

2022-04-04 14:20 UTC, justaugustus commented on README.md
>  added in the future.
```suggestion
The currently supported formats are `default` (table) and `json`.
```

2022-04-04 14:44 UTC, lehors commented on README.md
>  added in the future.
Done.

2022-04-19 05:50 UTC, lehors commented
> Tiny nits on the language. In addition to mentioning the format options, we should specify what `default` actually means (outputting as a table).
> 
> Could you mention this in the flags as well?

@justaugustus  Done. Thanks.

2022-05-09 11:51 UTC, lehors commented
I realize this isn't the most exciting PR maintainers might dream of but I would advise them to be a bit more diligent in merging PRs from the community. It is not a very pleasant experience to have to keep rebasing your PRs because it is being left unattended by the maintainers. @justaugustus could you please help?
Thanks.

2022-05-09 12:07 UTC, justaugustus approved these changes
> I realize this isn't the most exciting PR maintainers might dream of but I would advise them to be a bit more diligent in merging PRs from the community. It is not a very pleasant experience to have to keep rebasing your PRs because it is being left unattended by the maintainers.

Thanks for the PR, @lehors!
As a note, several of the maintainers are preparing for conferences and other events, hence the delayed reviews.

2022-05-09 12:15 UTC, merged