Enable gosec in golangci-lint
ossf/scorecard pull request #185
Opened 2021-02-16 11:22 UTC by endorama

- **Please check if the PR fulfills these requirements**

* [ ] Tests for the changes have been added (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

CI improvement

- **What is the current behavior?** (You can also link to an open issue here)

`gosec` linter is not enabled #172

- **What is the new behavior (if this is a feature change)?**

`golangci-lint` runs `gosec` linter

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

no

- **Other information**:

Closes #172

2021-02-16 13:12 UTC, naveensrinivasan requested changes
Thank you! Could you please squash the commits into 1 commit?

2021-02-16 13:12 UTC, naveensrinivasan commented on .github/workflows/golangci-lint.yml
> +          args: --timeout=5m --enable=gosec
There is another PR with all the linters enabled https://github.com/ossf/scorecard/pull/184. Could you please remove this? The other one should take of gosec also.

2021-02-19 09:51 UTC, endorama commented
@naveensrinivasan removed offending commit. 1 commit left with the `nosec` exclusion.

2021-02-19 13:19 UTC, naveensrinivasan commented
/ok-to-test sha=5b37af4

2021-02-19 13:22 UTC, naveensrinivasan approved these changes
Thank you!

2021-02-19 13:23 UTC, merged