✨ Add DangerousWorkflow check for imposter commits.
ossf/scorecard pull request #2789
Opened 2023-03-24 20:45 UTC by wlynch

#### What kind of change does this PR introduce?

Adds DangerousWorkflow check for imposter commits.
    
See https://www.chainguard.dev/unchained/what-the-fork-imposter-commits-in-github-actions-and-ci-cd

This borrows its implementation from
https://github.com/chainguard-dev/clank to look up imposter commits for
a repo.

(Is it a bug fix, feature, docs update, something else?)

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

n/a (new check)

#### What is the new behavior (if this is a feature change)?**

- [x] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

Fixes #2733 

#### Special notes for your reviewer

GitHub e2e test is failing because the Actions yaml is testing against isn't actually valid (it references non-existent repos). We should fix this, but figure get this PR out for review.

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
Adds new DangerousWorkflow check for detecting imposter commits.
```

2023-03-24 22:31 UTC, spencerschrock requested changes
Not a complete review, but wanted to get some comments out that address some big blockers with this current implementation. This change will likely require converting `Dangerous-Workflow` away from a file content only check:
https://github.com/ossf/scorecard/blob/eb57e04ac487a76f4dd71aa3cdfc2806c5cd5076/checks/dangerous_workflow.go#L28-L32

I'll also post some thoughts in the main issue for this PR that are better suited there.

2023-03-24 22:31 UTC, spencerschrock commented on clients/gitlabrepo/client.go
> +	if err := newClient.InitRepo(repo, commitSHA, commitDepth); err != nil {
similar concerns

2023-03-24 22:53 UTC, spencerschrock commented
I agree with the need for a sub-`RepoClient`, as we're trying to answer the question "does this commit belong to repo B" but I'm not sure how I feel about the current approach. A new method like `NewClient` makes sense since `RepoClient` might be a github/gitlab/local etc, but I'm wondering if there's a way we can make the child `RepoClient` lighter. 

If we modify RepoClient so the struct fields are optional that could help:

e.g.
```
if client.graphClient != nil {
    client.graphClient.init(client.ctx, client.repourl, client.commitDepth)
}
```

In the GitHub implementation for example,  the `ContainsRevision` method only uses the `branchesHandler` handler. It does it to read `repourl` which is already a member of `Client`, so we could even eliminate the need to use `branchesHandler`.

2023-03-24 22:54 UTC, spencerschrock commented
I think it makes sense to discuss this some more before re-implementing things.

2023-04-03 21:16 UTC, wlynch commented
For the repo client - good to know that the handlers are stateful. I think we could probably get a fresh client if we just refactor some of the client initialization from here - https://github.com/ossf/scorecard/blob/b6362b14ee0bc2dd2d6d3fbc7ccff7fbd7cd57ae/clients/githubrepo/client.go#L265-L309

The main piece we want to reuse is the authed client, which we can pick out from the client struct. I'll take a pass at it. (also open to other ideas)

2023-04-03 21:28 UTC, wlynch commented on clients/githubrepo/client.go
> +	if err := newClient.InitRepo(repo, commitSHA, commitDepth); err != nil {
Refactored this to use the same handler creation logic as CreateGithubRepoClientWithTransport. PTAL!

2023-04-03 21:29 UTC, wlynch commented
> This change will likely require converting Dangerous-Workflow away from a file content only check:

Looks like CommitBased / FileBased are the only 2 types at the moment. https://github.com/ossf/scorecard/blob/eb57e04ac487a76f4dd71aa3cdfc2806c5cd5076/checker/check_request.go#L40-L45

I assume we'll need to make a new one? Any suggestions for what this new type should be? `APIBased`?

2023-04-03 21:37 UTC, spencerschrock commented
> > This change will likely require converting Dangerous-Workflow away from a file content only check:
> 
> Looks like CommitBased / FileBased are the only 2 types at the moment.
> 
> https://github.com/ossf/scorecard/blob/eb57e04ac487a76f4dd71aa3cdfc2806c5cd5076/checker/check_request.go#L40-L45
> 
> I assume we'll need to make a new one? Any suggestions for what this new type should be? `APIBased`?

I meant more along the lines of removing `FileBased` from the `Dangerous-Workflow` check as it now requires the API call. I don't think we need an `APIBased` as every check is assumed to be API based unless FileBased is declared.

https://github.com/ossf/scorecard/blob/b6362b14ee0bc2dd2d6d3fbc7ccff7fbd7cd57ae/checks/dangerous_workflow.go#L28-L32

Which is a little unfortunate, as there's still plenty of functionality which works on the file content. Scorecard would benefit from some sort of "optional API call" as once a check removes support for `FileBased` it can't be run locally.

```
go run main.go --local=. --checks Dangerous-Workflow
Error: GetEnabled: internal error: Unsupported RequestType [0] by check: Dangerous-Workflow
2023/04/03 14:35:00 error during command execution: GetEnabled: internal error: Unsupported RequestType [0] by check: Dangerous-Workflow
```

2023-04-03 21:42 UTC, spencerschrock commented
> For the repo client - good to know that the handlers are stateful. I think we could probably get a fresh client if we just refactor some of the client initialization from here -
> 
> https://github.com/ossf/scorecard/blob/b6362b14ee0bc2dd2d6d3fbc7ccff7fbd7cd57ae/clients/githubrepo/client.go#L265-L309
> 
> The main piece we want to reuse is the authed client, which we can pick out from the client struct. I'll take a pass at it. (also open to other ideas)

Agree that extracting the auth'd transport is the main bit we care about. I'll take a look at any follow-up commits later.

We can always revisit the optional `init()` comment if performance becomes a problem. The tarball handler's init function for example downloads the tarball and extracts it to a `/tmp` directory. So all of these subclients would be doing extra work when we really just care about is making an API call using the auth from the main client.

2023-04-03 21:43 UTC, spencerschrock commented
Disregard about the tarball client, it's loaded lazily so shouldn't be a problem

2023-04-04 19:52 UTC, spencerschrock reviewed
The NewClient approach looks good to me. 

I've left some comments on the ref parsing, with regard to re-usable workflows (which should be vulnerable to imposter commits) as well as filtering out non commit SHA refs.

And finally, the increased quota would likely be a problem for running this check in the cron so want to get some input from @azeemshaikh38 on that one.

2023-04-04 20:01 UTC, spencerschrock commented on checks/raw/dangerous_workflow.go
> +			sha := s[1]
would also need to force `sha` to lowercase, or account for it in the regex

2023-04-06 16:35 UTC, azeemshaikh38 reviewed
Some high-level comments about code architecture:

- We could avoid changes to the `RepoClient` interface altogether and instead inject a new dependency in [RunScorecard](https://github.com/ossf/scorecard/blob/main/pkg/scorecard.go#L84) fn.
- For the cron job, we can later optimize this injected dependency with a more API efficient model (like a blobstore-based cache maybe) while regular CLI continues to use REST API.
- Flag-guard this change so that it does not get rolled out to prod without some testing on our end.

2023-04-06 16:35 UTC, azeemshaikh38 commented on checks/dangerous_workflow.go
> -	if err := registerCheck(CheckDangerousWorkflow, DangerousWorkflow, supportedRequestTypes); err != nil {
+1

2023-04-06 16:35 UTC, azeemshaikh38 commented on clients/repo_client.go
> +	NewClient(repo string, commitSHA string, commitDepth int) (RepoClient, error)
I'm not sure I understand the usecase for `NewClient` API. Could we not use `CreateGitHubRepoClient` instead?

2023-04-06 16:35 UTC, azeemshaikh38 commented on checks/raw/dangerous_workflow.go
> +		for _, step := range job.Steps {
Reusable workflows can't be hash pinned. Would be interesting to check whether the imposter commit holds true for reusable workflows too.

2023-04-06 16:49 UTC, spencerschrock commented on checks/raw/dangerous_workflow.go
> +		for _, step := range job.Steps {
Taken from the docs:
> {ref} can be a SHA, a release tag, or a branch name.

And an experiment I did last year for a different reason
https://github.com/spencerschrock/reusable-workflow-caller/blob/aa0ccd0b1d5255d79a7ba32fd729a1db93d2f124/.github/workflows/scorecard.yml#L30

2023-05-07 01:57 UTC, closed without merging