Checker plugins using go plugins
ossf/scorecard pull request #3809
Opened 2024-01-18 20:22 UTC by pdxjohnny

#### What kind of change does this PR introduce?

- feat: expose checker registration
- feat: enable checker go plugins

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

- Checks must be added in tree within upstream scorecard repo

#### What is the new behavior (if this is a feature change)?**

- [ ] Plugins can be loaded by specifying a `SCORECARD_DYNAMIC_CHECKS`
  environment variable which leverages Golang plugins
- [ ] Docs have been added
- [ ] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

#### Special notes for your reviewer

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note

```

2024-01-18 20:25 UTC, pdxjohnny commented on checks/dynamic.go
> +const CheckDynamicPluginLocationEnvironmentVariable = "SCORECARD_DYNAMIC_CHECKS"
- [ ] Rename to `checks/plugins.go`

2024-01-18 21:30 UTC, spencerschrock requested changes
We are trying to avoid using plugins for the reasons specified in #3095

2024-01-18 21:32 UTC, spencerschrock commented
cc @naveensrinivasan for possible coordination

2024-01-18 21:52 UTC, pdxjohnny commented
Thanks @spencerschrock, so just to clarify focus of this PR would be on the check docs side of things?

2024-01-18 22:34 UTC, spencerschrock commented
> Thanks @spencerschrock, so just to clarify focus of this PR would be on the check docs side of things?

There's still the aspect of the changes outlined in #3095, and the followup comment https://github.com/ossf/scorecard/issues/3095#issuecomment-1571046576.

2024-02-07 19:40 UTC, naveensrinivasan commented
I apologize for the delayed response. I will be working on this. Thanks!

2024-02-07 22:42 UTC, pdxjohnny commented
Should I close this PR then?

On Wed, Feb 7, 2024 at 11:40 Naveen ***@***.***> wrote:

> I apologize for the delayed response. I will be working on this. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ossf/scorecard/pull/3809#issuecomment-1932744013>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABNMXYMCNICMJJ6J56Q5ENDYSPKCXAVCNFSM6AAAAABCA4DPX6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZSG42DIMBRGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-26 22:04 UTC, spencerschrock commented
> Should I close this PR then?

I'm not sure about Naveen's expected timeline, but I'll go ahead and close this for now. 
@naveensrinivasan can you update us if you dont end up pursuing this?

2024-02-26 22:04 UTC, closed without merging